version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: pizza
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: pizza-store
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
    ports:
      - 33060:3306
    networks:
      - net

  redis:
    image: redis
    ports:
    - "6379:6379"
    networks:
      - net

  nestjs:
    image: node:12-alpine
    working_dir: /pizza-store
    volumes:
      - ../:/pizza-store
    command: "npm run start:debug"
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - mysql
      - redis
    networks:
      - net
networks:
  net:
    driver: bridge

